baseURL = 'https://example.org/'
languageCode = 'en-gb'
title = 'Integrated Kun Tao'
theme = 'ikt'

[[menus.main]]
name = 'News'
pageRef = '/news'
weight = 10

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 20

[[menus.main]]
name = 'Ricky Crofts'
pageRef = '/ricky'
weight = 30

[[menus.main]]
name = 'Lineage'
pageRef = '/brian'
weight = 40

[[menus.main]]
name = 'Classes'
pageRef = '/classes'
weight = 50

[[menus.main]]
name = 'Contact'
pageRef = '/contact'
weight = 60
